### ISSUE TITLE
How can I get online MinCostFlow result?

### ISSUE THREAD

**Issue by AnkyZhang** [nightmaredimple/libmot#2]
Hi, Thx for your sharing on [zhihu](https://zhuanlan.zhihu.com/p/111397247) .
I found that "scripts/test_epipolar_geometry.py" is offline MinCostFlow Tracker. 
How can I get online MinCostFlow result?

**Comment by nightmaredimple** [comment]
Because the online MinCostFlow is similar as to the LinearAssignment. You can try Line76-77 in "scripts/test_kalman_tracker.py".

**Comment by nightmaredimple** [comment]
> Hi, Thx for your sharing on [zhihu](https://zhuanlan.zhihu.com/p/111397247) .
> I found that "scripts/test_epipolar_geometry.py" is offline MinCostFlow Tracker.
> How can I get online MinCostFlow result?

Because the online MinCostFlow is similar as to the LinearAssignment. You can try Line76-77 in "scripts/test_kalman_tracker.py".
