### ISSUE TITLE
iou_assignment这个是怎么使用的？

### ISSUE THREAD

**Issue by kingmacth** [nightmaredimple/libmot#3]
您好！
我没有看到哪里调用了这个函数呢。想测试一下这个的效果

**Comment by nightmaredimple** [comment]
LinearAssignment -> GreedyAssignment
https://github.com/nightmaredimple/libmot/blob/23b8e2ac00f8b45d5a0ecabd57af90585966f3ff/scripts/test_kalman_tracker.py#L76
