### ISSUE TITLE
关于ECC的问题

### ISSUE THREAD

**Issue by monsters-s** [nightmaredimple/libmot#4]
你好，首先谢谢分享，我在使用ECC的时候有一个问题，我在这个链接：
https://blog.csdn.net/full_speed_turbo/article/details/68484450
查阅到了python版本的ECC代码，我感觉楼主的代码应该是借鉴了一部分这个连接的代码，但是我对比两版代码之后发现一个问题，就是首先两个代码都是输入第一张图片和第二张图片，然后进行求解仿射变换矩阵，但是博主的代码是将src图像乘以变换矩阵，得到dst图像的相似图像，链接中的代码是将img2的图像得到img图像的相似图像，就是博主的方法求得的仿射变换矩阵是src到dst的，但是链接的代码是img2到img1的，与我感觉的变换关系是相反的，所以来请教一下

**Comment by nightmaredimple** [comment]
please refer to [official api](https://docs.opencv.org/master/dc/d6b/group__video__track.html#ga1aa357007eaec11e9ed03500ecbcbe47)

**Comment by nightmaredimple** [comment]
Also notice the difference: WARP_INVERSE_MAP

**Comment by monsters-s** [comment]
谢谢博主，我没有注意到WARP_INVERSE_MAP，就是它的问题
